---
title:  "SYS 5581 Time Series and Forecasting"
author: "Instructor: Arthur Small"
date:   "University of Virginia Engineering, Spring 2021"

output: 
  pdf_document:
#   keep_tex: true
    fig_caption: yes
    latex_engine: pdflatex

  # html_document:
  #   keep_md: true

urlcolor: blue
geometry: margin=1in

fontfamily: mathpazo
fontsize: 11pt
header-includes:
   - \linespread{1.05}
---

```{r setup, include=FALSE, cache=F, message=F, warning=F, results="hide"}
knitr::opts_chunk$set(cache=TRUE)
knitr::opts_chunk$set(fig.path='figs/')
knitr::opts_chunk$set(cache.path='_cache/')
knitr::opts_chunk$set(warning=F, message=F)
# knitr::opts_knit$get(kable.force.latex = TRUE)
```

*Class meetings:* MW 09:30-10:45 a.m. online via Zoom

*Office Hours:* MW 11:00 a.m.-12:30 p.m. online via Zoom (subject to change). Sign up in advance for a 45-minute session via the Collab "Sign Up" tool. If you cannot make any scheduled time, please contact the instructor via email to schedule an appointment. Meetings online via Zoom: <https://virginia.zoom.us/my/arthursmalliii>

*Web Resources:*

  * [Collab class site](https://collab.its.virginia.edu), for basic course information, assignments, office hours sign-up, links to online textbook and other resources.
  * [Github class site](https://github.com/uva-eng-time-series-sp21), for posting and sharing code.
  * Zoom, for class sessions, recordings, and office hours.

# Course Description

The course is designed to introduce graduate students and advanced undergraduates in engineering to time series and forecasting. The course will not include a deep exploration of theory. Rather, the goal is for students by the end to be able to analyze time series data competently, as part of their work designing and working with engineered systems. 

In addition to learning theory, each student will undertake a semester-long research project. Ideally, this project will relate closely to the student’s own dissertation research, professional practice, or other domain application that interests them. My hope is that these projects could form the basis for subsequent research papers, dissertation chapters, or other professional work products, for interested students.

The course will, therefore, be structured primarily as a *workshop*: the ultimate goal is to help you to create a professionally presented report. Our workflow will, therefore, be subject to revision, according to my judgement of how best to use our time to help you produce a professional report.

The course outline is divided into two major sections. First, we will introduce the theory, with examples. In the later part of the semester, we will focus on workshopping your projects in progress.

Important: class readings are subject to change, contingent on mitigating circumstances and the progress we make as a class.  Students are encouraged to attend lectures and check the course website for updates. 


## Prerequisites

Students should have taken at least one rigorous intermediate course in probability and statistics. They should be comfortable with the representation of uncertain information in the form of probability distributions, with conditional probabilities, and with other such foundational concepts. 

In addition, to carry out the data analyis, the student should have at least ability be able to code, in some general-purpose language. For this course, we will work in R, focusing on specialized packages for working with time series data and generating forecasts.

## Expectations

Each student will make a presentation on their data analysis project. Students will be evaluated based on their performance in these presentations and on their final project, on occasional short quizzes; and on their contributions inside and outside of class towards helping other students. 

## Readings 

The primary text for the course will be [*Forecasting: Principles and Practice*, 3rd ed.](https://otexts.com/fpp3/) by
Rob J. Hyndman and George Athanasopoulos. This resource is available for free online and is linked from the Collab site. The text includes example code in R, and covers several useful R packages related to time series and forecasting.

Additional readings including relevant articles will be provided as the course progresses. The choice of readings will depend in part on student interests, as conveyed through their choice of projects. 

## Course Objectives

1. Students will learn the foundations of time series and forecasting.

2. Students will gain the experience of building statistical models of time series, and models for forecasting, and will learn how to evaluate their performance.

3. Students will learn the concepts and practice of *reproducible research*, in the course of preparing a research paper.

4. Students will gain experience in making presentations and in preparing a polished research article.


## Grading Policy

- **10%** of your grade will be determined by quizzes designed to test your understanding of the theoretical concepts introduced in class. This quiz will delivered at roughly the mid-point of the semester. It will be open-book and open-notes, outside of class. You will have multiple days to complete it. The quiz will not be designed to be especially challenging: the goal is to give you the opportunity to synthesize your understanding of core concepts, in preparation for developing your data analysis for your research project.

- **10%** of your grade will be determined by your performance in one in-class presentation based on your project. These presentations will be scheduled when you are, in the judgement of the instructor, far enough along to do so.

- **10%** of your grade will be determined by your contributions to assist other students. These contributions can come through class participation, by making useful contributions in online forums (Github), or through other means that add value to the group experience.

- **70%** of your grade will be determined by your performance on your final project. The development of the project will include multiple iterations, each with an associated deliverable: 

  * An initial Concept Note.
  * A more developed Project Proposal.
  * A first working draft of your final project paper.
  * A final complete draft of your project paper.

Details of these staged intermediate deliverables will be forthcoming. The final product should be a polished professional paper that meets academic standards regarding format, quality, and integrity.


## Attendance Policy

> *Showing up is 80 percent of life* -- Woody Allen, [via Marshall Brickman](http://quoteinvestigator.com/2013/06/10/showing-up/#note-6553-1)

Regular attendance is very much in your pedagogic interest. However, it is up to you whether to attend in person or to view recorded class sessions afterwards.

## Communications protocols, including emails and office hours

I prefer to avoid using email to communicate with students about class matters. For substantive questions about course materials and concepts, please use class time, office hours, or meetings by appointment. Please use email only for brief clarifying questions, or to set up appointments. 

## Academic Dishonesty Policy

Don’t cheat. Don't plagiarize. Don't present someone else's work as your own.

## Disabilities Policy

Together with the University of Virginia, I am committed to assuring that all students have the full opportunity to benefit from the course regardless of their disability status. If you have a disability that may require accommodations, please see the instructor early in the semester to work out appropriate arrangements.



